# Generated by Django 5.2.11 on 2026-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='emprestimo_andamento',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.BooleanField(default=1, verbose_name='Status do empréstimo'),
            preserve_default=False,
        ),
    ]
