# Generated by Django 5.2.11 on 2026-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_emprestimo_emprestimo_andamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Devolvido')], default=True, verbose_name='Status do empréstimo'),
        ),
    ]
