# Generated by Django 5.2.11 on 2026-03-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_emprestimo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='data_plub',
            new_name='data_pub',
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.BooleanField(choices=[(True, 'Disponível'), (False, 'Indisponível')], default=True, verbose_name='Status do livro'),
        ),
    ]
